<!DOCTYPE html> 
<html lang="es">
    <head>
        <meta charset="utf-8">
        <title>Ship2b | Mapa de iniciativas</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="shortcut icon" href="/img/common/favicon.ico">



        <!-- Bootstrap core CSS -->
        <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet">

        <!-- Custom styles for this template -->
        <link href="/css/styles.css" rel="stylesheet">

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>

    <body>
        
<div style="
height:100%;
width:100%;">

    <img src="img/beta_banner.png" class="beta_banner">

</div> 

        
        
        <div class="container">
            
            
            <div class="content">

                <header class="row">
                   
                    <div class="col-md-4 col-md-push-8  header_ship2">
                        <a href="http://www.ship2b.org" target="_blank" class="ship2b_logo"><img src="/img/header/header_ship2b.png" class="img-responsive"  /></a>
                            
                        <div id="social_sel_list" >
                                    <ul>
                                        <li class="social_fb"><a href="https://www.facebook.com/ship2b?fref=ts" target="_blank"><img src="/img/header/facebook.png" /></a></li>
                                        <li class="social_twitter"><a href="https://twitter.com/ship2B" target="_blank"><img src="/img/header/twitter.png" /></a></li>
                                        <li class="social_rss"><a href="http://www.ship2b.org/feed/?lang=es" target="_blank"><img src="/img/header/rss.png" /></a></li>
                                    </ul>
                                </div>
                    </div>
                    <div class="col-md-8 col-md-pull-4  map_logo">
                        <img src="/img/header/title_mapa_es.png" class="img-responsive" />
                    </div>
                   
                </header>
                <div class="content-pad">
                    <?php echo $this->layout()->content; ?>
                </div>
                
                
                <footer >
                    <ul>
                        <li ><a target="_blank" href="http://www.ship2b.org/ship2b-2/">Ship2B</a></li>
                        <li ><a target="_blank" href="http://www.ship2b.org/far/">Far</a></li>
                        <li ><a target="_blank" href="http://www.ship2b.org/programes/">Programes</a></li>
                        <li ><a target="_blank" href="http://www.ship2b.org/b-angels/">B-Angels</a></li>
                        <li ><a target="_blank" href="http://www.ship2b.org/flota-2/">Flota</a></li>
                        <li ><a target="_blank" href="http://www.ship2b.org/far/bsessions/">B-Sessions</a></li>
                        <li ><a target="_blank" href="http://www.ship2b.org/blog-3/">Blog</a></li>
                        <li ><a target="_blank" href="http://www.ship2b.org/contacte/">Contacte</a></li>               
                    </ul>
                </footer>
            </div>

        </div>

    </body>



</html>    





